### ISSUE TITLE
How to make circle instead of rectangle to the focused icon 

### ISSUE THREAD

**Issue by ghost** [mreram/ShowCaseView#18]
How to make circle instead of rectangle to the focused icon for the tutorial, is there any method or its by default rectangle? 
![circle](https://user-images.githubusercontent.com/32764496/51609647-a2ba5800-1f40-11e9-923b-bba37f79364c.png)

**Comment by mreram** [comment]
Dear @trayfullstackdevs ,
Currently, there is no any method for using circle instead of rectangle but it's in the roadmap.

**Comment by mreram** [comment]
Dear @trayfullstackdevs ,
Currently, there is not any method for using circle instead of rectangle but it's in the roadmap.

**Comment by ArjunBhilare** [comment]
When will the changes from JJSWART/ShowCaseView be included in this library? Since in the current version we are unable to change the background color or the Message Box Background

**Comment by mreram** [comment]
This feature already exists please check the sample app.
