### ISSUE TITLE
how to use it with MenuItem NavigationView?

### ISSUE THREAD

**Issue by firmaan** [mreram/ShowCaseView#19]
Hi, i'm using your nice library, but how to use it with MenuItem **Profil Saya** NavigationView?

Thanks

![edit](https://user-images.githubusercontent.com/34561434/51648749-688a9e00-1fb4-11e9-8257-4ba6801fda83.jpg)

**Comment by mreram** [comment]
Hi @firmaan , this library is designed for View(s) and only supports View reference. 
For this case, you should find View reference from NavigationView.
Example:
```
int itemViewsStartingPosition = 0;
for (int i = 0; i < navigationView.getChildCount(); i++) {
    if (navigationView.getChildAt(i) instanceof NavigationMenuItemView) {
        itemViewsStartingPosition = i;
        break;
    }
}
View targetView = ((NavigationMenuView) navigationView.getChildAt(itemViewsStartingPosition)).getChildAt(1);
Log.i("targetView",targetView.toString());
new GuideView.Builder(MainActivity.this)
        .setTargetView(targetView)
        .setGravity(Gravity.center)
        .setTitle("Title!")
        .setContentText("Description...")
        .build()
        .show();           
```
![ezgif-5-dc8e24b35dbc](https://user-images.githubusercontent.com/11220808/51672586-157b1000-1fe1-11e9-8416-b4d6513818b0.gif)

**Comment by firmaan** [comment]
thanks for quick response, i tried but i got error 
<pre>Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.view.View.toString()' on a null object reference</pre>

its my code MainActivity.java in onCreate
```
View targetView = ((NavigationMenuView) navigationView.getChildAt(0)).getChildAt(1);
Log.i("targetView",targetView.toString());
new GuideView.Builder(this)
                .setTitle("Lengkapi Profil Anda")
                .setContentText("informasi akan menampilkan sesuai dengan skill anda")
                .setGravity(Gravity.center) 
                .setDismissType(DismissType.targetView) 
                .setTargetView(targetView)
                .build()
                .show()
```
its my code menu_navigation.xml
```
<group android:checkableBehavior="single">
        <item
            android:id="@+id/profilSaya"
            android:icon="@drawable/nav_person"
            android:tint="@color/btngrey"
            android:checkable="false"
            android:title="Profil Saya" />
        <item
            android:id="@+id/aboutapp"
            android:icon="@drawable/nav_about"
            android:tint="@color/btngrey"
            android:checkable="false"
            android:title="Tentang Aplikasi" />
        <item
            android:id="@+id/logout"
            android:icon="@drawable/nav_exit"
            android:tint="@color/btngrey"
            android:checkable="false"
            android:title="Keluar" />
    </group>
```

**Comment by mreram** [comment]
Dear @firmaan, You should put the code in right place (inflated navigation view). For example you should put the code in onDrawerOpened method of DrawerListener.

**Comment by firmaan** [comment]
thank you very much, you made my day :D
 
![screenshot_sistem_informasi_pencarian_kerja_20190124-202045](https://user-images.githubusercontent.com/34561434/51681057-17ab9180-2016-11e9-9596-bbdc50cc8361.png)
