### ISSUE TITLE
OnClick in showcase

### ISSUE THREAD

**Issue by raldeskrisnu** [mreram/ShowCaseView#20]
hallo, how add click listener in showcase? i need click listener for add sharedpreference 

thanks

**Comment by mreram** [comment]
hi @raldeskrisnu , you can use the onDismiss method of GuideListener.
```
setGuideListener(new GuideListener() {
                      @Override
                      public void onDismiss(View view) {
                         //TODO ...
                      }
                   })
```

**Comment by mreram** [comment]
Currently, by default the gravity is Center but you can fork the repo and make the your changes. in this case you should to change some attribute in GuideMessageView class.
