### ISSUE TITLE
How to dismiss showcaseview and move to next 

### ISSUE THREAD

**Issue by suyashm002** [mreram/ShowCaseView#3]
Hey its is a good library but i didn't find how to dismiss showcase view t

**Comment by mreram** [comment]
hi thanks, you can call dismiss() method on instance of GuideView example:
`
GuideView  mGuideView = builder.build();
mGuideView.dismiss();
`

you can see sample usage: 
https://github.com/mreram/ShowCaseView/blob/master/app/src/main/java/ir/smartdevelop/eram/showcaseview/MainActivity.java
