### ISSUE TITLE
error on drawing arrow when i click on view

### ISSUE THREAD

**Issue by yosefghobadi20** [mreram/ShowCaseView#30]
sorry for my weak English
during the drawing arrow, if you click on the view you throw out the app

**Comment by mreram** [comment]
Dear Yosef,
Thanks for your feedback, Are you test on my sample app?

یوسف جان ، ممنونم از فیدبکت 
روی اپ سمپل من داری تست میکنی؟

**Comment by mreram** [comment]
Dear Yosef,
Thanks for your feedback, Are you testing on my sample app?

یوسف جان ، ممنونم از فیدبکت
روی اپ سمپل من داری تست میکنی؟

**Comment by mreram** [comment]
Dear @yosefghobadi20 
If there is no problem this issue will be closed.

**Comment by yosefghobadi20** [comment]
سلام روی اپ خودم تست کردم
