### ISSUE TITLE
Every time Open app it is showing the showcaseview why?

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [mreram/ShowCaseView#35]
hi I am trying to add your library in my application working well but i have seeing that it show the same dialog everytime i am opening the application pls help me here ,
I want it to open only the first time my code is

    private void ShowIntro() {

        new GuideView.Builder(MainActivity.this)
                .setTitle("Warning")
                .setContentText("Supported Language for Extract Text from pdf are  Catalan\n" +
                        "Danish\n" +
                        "Dutch\n" +
                        "Turkish")
                .setTargetView(findViewById( R.id.fab))
                
                .setDismissType( DismissType.anywhere) //optional - default dismissible by TargetView
                .setGuideListener(new GuideListener() {
                    @Override
                    public void onDismiss(View view) {
                        Toast.makeText( getApplicationContext(),"Click",Toast.LENGTH_LONG ).show();
                    }
                })
                .build()
                .show();
    }

**Comment by mreram** [comment]
Hi,
You must implement a mechanism for handle this situation. For example you can use SharedPreferences.

**Comment by sunil-singh-chaudhary** [comment]
yes i know that , thanks but you have to add this on predefined library because it is the behavior of every showcaseview
