### ISSUE TITLE
How to end showcase ?

### ISSUE THREAD

**Issue by mdriken** [mreram/ShowCaseView#39]
does anyone have try after the showcase finish, it not show again if we open the app?

**Comment by inurcahyo18** [comment]
You can make flag for this issue,
example:
if(showCaseShown){

 #script showCase

}
showCaseShown = false;

**Comment by nasserkhoshfetrat** [comment]
in the last **onDissmiss** of **TargetView** simply return (or persistent in sdcard to not show in the next run
