### ISSUE TITLE
Not able to dismiss nor there is any way for continuity

### ISSUE THREAD

**Issue by suyashm002** [mreram/ShowCaseView#4]
I am using  mGuideView = builder.build();
                        mGuideView.dismiss();

but unable to dismiss this it is  not working . And what if i want to show other icon after how can i do that to maintain continues behaviour . I am using this in fragment

**Comment by mreram** [comment]
maybe using wrong instance of GuideView.
Could you show me your code ?

**Comment by mreram** [comment]
and you can see sample code for continuity
https://github.com/mreram/ShowCaseView/tree/master/app

**Comment by suyashm002** [comment]
I am using the same code but in fragment and when click anywhere it is not dismissed

**Comment by mreram** [comment]
my idea was dismissible by clicking on target view
but my future plan is dismissible by clicking outside..

**Comment by suyashm002** [comment]
Thank you mreram, nice library . And thanks for quick response let me know if i can contribute to this project to make it more better

**Comment by mreram** [comment]
Thanks,
Pull requests are welcome! 
You can improve/fix some part of it .

Add Tests: 
Assuming that the code in question already has automated (unit) tests, do add tests for the code you submit. 
This isn't a hard rule. There are various cases where you may need to add code without test coverage (e.g. when adding a Object), but if it can be tested, it should be tested.

**Comment by mreram** [comment]
#3 added Dismiss Type
