### ISSUE TITLE
Dark Theme Bug

### ISSUE THREAD

**Issue by ImTema** [mreram/ShowCaseView#42]
noticed bug with dark theme

![image](https://user-images.githubusercontent.com/11259150/94847713-9d0e5880-042b-11eb-8f41-a74db67c4f76.png)

the simpliest workaround is to set transparent background for `GuideMessageView.java` for TextViews
```java
mTitleTextView.setTextColor(Color.BLACK);
mTitleTextView.setBackgroundColor(Color.TRANSPARENT);
...
 mContentTextView.setGravity(Gravity.CENTER);
 mContentTextView.setBackgroundColor(Color.TRANSPARENT);
```
and result of above code is 

![image](https://user-images.githubusercontent.com/11259150/94847987-ffffef80-042b-11eb-92f9-09da8a426319.png)

**UPDATE:**

i have troubles with "Pull Request"s, sorry T_T

**Comment by mreram** [comment]
This library doesn't support dark mode, but it is open-source, and I accept pull requests.
