### ISSUE TITLE
Bug: places the guide outside of the screen

### ISSUE THREAD

**Issue by n-khosh** [mreram/ShowCaseView#43]
![Screenshot_1601668314](https://user-images.githubusercontent.com/23635655/94964133-2003e180-0506-11eb-8229-1259417b5e71.png)

**Comment by mreram** [comment]
It's a rare scenario because you don't have enough space on-screen and for example, the user need to scroll to see guidelines! so it's weird functionality but it's an open-source project and I accept PRs then if you have any suggestions or ideas please send your PR. 
Thanks, regards.
