### ISSUE TITLE
Could not find com.github.mreram:showcaseview:1.2.0.

### ISSUE THREAD

**Issue by sreyans01** [mreram/ShowCaseView#50]
Was working fine before upgrading to Android Studio to 4.2.0.

Below are the details shown in the error:

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.mreram:showcaseview:1.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/mreram/showcaseview/1.2.0/showcaseview-1.2.0.pom
       - https://jcenter.bintray.com/com/github/mreram/showcaseview/1.2.0/showcaseview-1.2.0.pom
       - https://repo.maven.apache.org/maven2/com/github/mreram/showcaseview/1.2.0/showcaseview-1.2.0.pom
       - https://oss.jfrog.org/libs-snapshot/com/github/mreram/showcaseview/1.2.0/showcaseview-1.2.0.pom
     Required by:
         project :app

**Comment by mreram** [comment]
Did you add jitpack repository in your build.gradle file?
```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
